services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: join-frontend
    restart: always
    expose:
      - 80
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.join.rule=Host(`join.veysel-karaali.com`)"
      - "traefik.http.routers.join.entrypoints=websecure"
      - "traefik.http.routers.join.tls.certresolver=myresolver"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.join.loadbalancer.server.port=80"

networks:
  traefik:
    external: true
